/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KitInicianteRouteImport } from './routes/kit-iniciante'
import { Route as EbooksTeatroRpgRouteImport } from './routes/ebooks.teatro-rpg'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KitInicianteRoute = KitInicianteRouteImport.update({
  id: '/kit-iniciante',
  path: '/kit-iniciante',
  getParentRoute: () => rootRouteImport,
} as any)
const EbooksTeatroRpgRoute = EbooksTeatroRpgRouteImport.update({
  id: '/ebooks/teatro-rpg',
  path: '/ebooks/teatro-rpg',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kit-iniciante': typeof KitInicianteRoute
  '/ebooks/teatro-rpg': typeof EbooksTeatroRpgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kit-iniciante': typeof KitInicianteRoute
  '/ebooks/teatro-rpg': typeof EbooksTeatroRpgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kit-iniciante': typeof KitInicianteRoute
  '/ebooks/teatro-rpg': typeof EbooksTeatroRpgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kit-iniciante' | '/ebooks/teatro-rpg'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kit-iniciante' | '/ebooks/teatro-rpg'
  id: '__root__' | '/' | '/kit-iniciante' | '/ebooks/teatro-rpg'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KitInicianteRoute: typeof KitInicianteRoute
  EbooksTeatroRpgRoute: typeof EbooksTeatroRpgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit-iniciante': {
      id: '/kit-iniciante'
      path: '/kit-iniciante'
      fullPath: '/kit-iniciante'
      preLoaderRoute: typeof KitInicianteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebooks/teatro-rpg': {
      id: '/ebooks/teatro-rpg'
      path: '/ebooks/teatro-rpg'
      fullPath: '/ebooks/teatro-rpg'
      preLoaderRoute: typeof EbooksTeatroRpgRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KitInicianteRoute: KitInicianteRoute,
  EbooksTeatroRpgRoute: EbooksTeatroRpgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
